---
- name: Install nscp
  chocolatey.chocolatey.win_chocolatey:
    name: nscp
    state: present

- name: The nsclient config file
  ansible.windows.win_template:
    src: nsclient.ini
    dest: "{{ nsclient_installed_location }}/nsclient.ini"
  notify: Restart nscp

- name: The nrpe_dh_2048.pem file
  ansible.windows.win_template:
    src: nrpe_dh_2048.pem
    dest: "{{ nsclient_installed_location }}/security/nrpe_dh_2048.pem"
    force: false
  notify: Restart nscp

- name: Enable ping through firewall
  ansible.windows.win_shell: |
    Enable-NetFirewallRule -DisplayName "File and Printer Sharing (Echo Request - ICMPv4-In)"
    Enable-NetFirewallRule -DisplayName "File and Printer Sharing (Echo Request - ICMPv6-In)"
  when: nagios_allow_ping
  changed_when: false
