---
# Variables ##########

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}-family.yml"

- name: Include Distribution version specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Set facts based on defaults  # noqa var-naming
  ansible.builtin.set_fact:
    "{{ item[8:] }}": "{{ lookup('vars', item) }}"
  when:
    - item is match("^default_")
    - vars[item[8:]] is not defined
  with_items: "{{ vars | list }}"

##########

- name: Include client
  ansible.builtin.import_tasks: client.yml
  when: >
    (nagios_client_enabled is defined and nagios_client_enabled | bool) or
    (nagios_client_enabled is not defined and run_nagios_client is defined)

- name: Include server
  ansible.builtin.import_tasks: server.yml
  when: >
    (nagios_server_enabled is defined and nagios_server_enabled | bool) or
    (nagios_server_enabled is not defined and run_nagios_server is defined)
