---
# Install check_nrpe
#

- name: Install check_nrpe from a package
  when:
    - check_nrpe_package is defined
  block:
    - name: Install check_nrpe package
      ansible.builtin.package:
        name: "{{ check_nrpe_package }}"
        state: present
        update_cache: true

    - name: Copy check_nrpe
      ansible.builtin.copy:
        src: "{{ nrpe_plugin_dir }}/check_nrpe"
        dest: "{{ nrpe_client_plugins_dir }}/check_nrpe"
        mode: '0755'
        owner: "{{ nagios_user }}"
        group: "{{ nagios_group }}"
        remote_src: true

- name: Install check_nrpe from source
  when:
    - check_nrpe_package is not defined
  block:
    - name: Ensure download directory is present
      ansible.builtin.file:
        path: "{{ nagios_download_dir }}"
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Include OS-specific variables.
      ansible.builtin.include_vars: "{{ ansible_os_family }}-family.yml"

    - name: Import setup-RedHat-family-prerequisites.yml
      ansible.builtin.import_tasks: setup-RedHat-family-prerequisites.yml
      when: ansible_os_family == 'RedHat'

    - name: Import setup-Debian-family-prerequisites.yml
      ansible.builtin.import_tasks: setup-Debian-family-prerequisites.yml
      when: ansible_os_family == 'Debian'

    - name: Get NRPE
      ansible.builtin.get_url:
        timeout: 30
        url: "{{ nrpe_url }}"
        dest: "{{ nagios_download_dir }}/{{ nrpe_src }}.tar.gz"
        mode: 0755
      retries: 3
      delay: 40
      register: result
      until: result is not failed

    - name: Unpack NRPE source files
      ansible.builtin.shell: cd {{ nagios_download_dir }} && tar -xzvf {{ nrpe_src }}.tar.gz creates={{ nagios_download_dir }}/{{ nrpe_src }}

    - name: Configure NRPE
      ansible.builtin.shell: ./configure --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu  # noqa command-instead-of-shell
      args:
        chdir: "{{ nagios_download_dir }}/{{ nrpe_src }}"
        creates: "{{ nagios_download_dir }}/{{ nrpe_src }}/Makefile"

    - name: Make NRPE
      ansible.builtin.shell: cd {{ nagios_download_dir }}/{{ nrpe_src }} && make all creates={{ nagios_download_dir }}/{{ nrpe_src }}/src/check_nrpe

    - name: Ensure plugins directory is present
      ansible.builtin.file:
        path: "{{ nrpe_client_plugins_dir }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy check_nrpe
      ansible.builtin.copy:
        src: "{{ nagios_download_dir }}/{{ nrpe_src }}/src/check_nrpe"
        dest: "{{ nrpe_client_plugins_dir }}/check_nrpe"
        mode: '0755'
        owner: "{{ nagios_user }}"
        group: "{{ nagios_group }}"
        remote_src: true
