---
- name: Collect Facts
  hosts: all:!windows:!blackbox
  remote_user: ubuntu
  become: true
  tasks:
    - name: Collect facts
      ansible.builtin.setup:

- name: Collect Facts Windows
  hosts: windows
  tasks:
    - name: Collect facts
      ansible.builtin.setup:

- name: Monitoring Servers (install client)
  hosts: monitoring-servers
  become: true
  roles:
    - {role: 'sdarwin.nagios', run_nagios_client: true}

- name: Monitoring Servers
  hosts: monitoring-servers
  remote_user: ubuntu
  become: true
  roles:
    # this is the Ansible Galaxy name, you could change it to Ansible-Nagios if directly downloading from github
    - {role: 'sdarwin.nagios', run_nagios_server: true}
